apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
subsets:
  - addresses:
      - ip: ${ENDPOINT}
    ports:
      - port: 8443
