name: Code Quality

on:
  pull_request:
    branches:
    - "main"
  push:
    branches: 
    - "*"

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
    - name: Lint README
      run: markdownlint README.md

  code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        pip install -e .
    - name: Lint application with flake8
      run: |
        flake8 src --count --show-source --statistics
    - name: Check application with mypy
      run: |
        mypy src
    # - name: Lint tests with flake8
    #   run: |
    #     flake8 tests --count --show-source --statistics
    # - name: Check tests with mypy
    #   run: |
    #     mypy tests
    # - name: Test with pytest
    #   run: |
    #     python -m pytest
